### ISSUE TITLE
[docs] flyway 적용 yml

### ISSUE THREAD

**Issue by gunwoong1630** [prgrms-be-devcourse/NBE5-7-3-Team06#87]
```
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

```
